# Generated by Django 5.2.7 on 2025-10-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_amount_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.AddField(
            model_name='topic',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='topic_ppts/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='topic_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_level',
            field=models.CharField(choices=[('6-8', 'Classes 6–8'), ('9-12', 'Classes 9–12')], max_length=5),
        ),
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.course'),
        ),
        migrations.AlterField(
            model_name='topiccompletion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
    ]
