# Generated by Django 5.2.5 on 2025-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_topic_content_topic_ppt_file_topic_video_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="caption_file",
            field=models.FileField(
                blank=True,
                help_text="Upload WebVTT (.vtt) captions",
                null=True,
                upload_to="topic_captions/",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="chapters_file",
            field=models.FileField(
                blank=True,
                help_text="Upload WebVTT (.vtt) chapters",
                null=True,
                upload_to="topic_chapters/",
            ),
        ),
    ]
