# Generated by Django 5.2.5 on 2025-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_topic_caption_file_topic_chapters_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="caption_file",
        ),
        migrations.AddField(
            model_name="topic",
            name="caption_en_file",
            field=models.FileField(
                blank=True,
                help_text="English captions (.vtt)",
                null=True,
                upload_to="topic_captions/",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="caption_ta_file",
            field=models.FileField(
                blank=True,
                help_text="Tamil captions (.vtt)",
                null=True,
                upload_to="topic_captions/",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="poster_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional poster/thumbnail",
                null=True,
                upload_to="topic_posters/",
            ),
        ),
    ]
