# Generated by Django 5.2.5 on 2025-11-02 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_mcqquestion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcqquestion",
            options={"ordering": ["topic__order", "id"]},
        ),
        migrations.AddField(
            model_name="mcqquestion",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Link MCQ to specific topic",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcqs",
                to="core.topic",
            ),
        ),
    ]
