# Generated by Django 5.2.5 on 2025-11-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_assignment_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: attach assignment to specific topic",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.topic",
            ),
        ),
    ]
