# Generated by Django 5.2.5 on 2025-11-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_assignment_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topiccompletion",
            name="assignment_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topiccompletion",
            name="assignment_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topiccompletion",
            name="mcq_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topiccompletion",
            name="mcq_passed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topiccompletion",
            name="video_watched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topiccompletion",
            name="video_watched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="topiccompletion",
            unique_together={("progress", "topic")},
        ),
    ]
