# Generated by Django 5.2.5 on 2025-11-05 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_topiccompletion_assignment_submitted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="certificate_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="final_exam_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="progress",
            name="final_exam_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="FinalExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Final Examination", max_length=200),
                ),
                ("num_questions", models.PositiveIntegerField(default=20)),
                (
                    "pass_mark",
                    models.PositiveIntegerField(
                        default=70, help_text="Percent required to pass"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_exam",
                        to="core.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="final_exam_images/"
                    ),
                ),
                ("option_1", models.CharField(max_length=255)),
                ("option_2", models.CharField(max_length=255)),
                ("option_3", models.CharField(max_length=255)),
                ("option_4", models.CharField(max_length=255)),
                (
                    "correct_option",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Option 1"),
                            (2, "Option 2"),
                            (3, "Option 3"),
                            (4, "Option 4"),
                        ]
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.finalexam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("passed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_exam_submissions",
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
