# Generated by Django 5.2.7 on 2025-10-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assignments_due',
            field=models.PositiveIntegerField(default=0, help_text='Number of pending assignments'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='impact_progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress in impact-related topics (0-100)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='payment_status',
            field=models.BooleanField(default=False, help_text='Indicates if the student has paid for access'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Overall progress percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stem_progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress in STEM subjects (0-100)'),
        ),
    ]
