# Generated by Django 5.1 on 2025-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_assignments_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_set',
            field=models.BooleanField(default=False, help_text='Whether admin has set a password for this student'),
        ),
    ]
